global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Configure entrypoints (Only Define Once)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Configure API and dashboard
api:
  dashboard: true
  insecure: false

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network
  file:
    watch: true

# Configure certificate resolvers (Only Define Once)
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: lolaayinde@gmail.com
#       storage: /acme.json
#       httpChallenge:
#         entryPoint: web

# Logging Configuration
log:
  level: INFO

accessLog: {}
