global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: lolaayinde@gmail.com
      storage: /acme.json
      tlsChallenge: {}

# Add this to traefik.yml
api:
  dashboard: true
  insecure: true
