global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Configure entrypoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Configure API and dashboard
api:
  dashboard: true
  insecure: false

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_default
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Configure certificate resolvers
certificatesResolvers:
  myresolver:
    acme:
      email: lolaayinde@gmail.com
      storage: /acme.json
      tlsChallenge: {}

log:
  level: INFO

accessLog: {}