global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik_network

certificatesResolvers:
  myresolver:
    acme:
      email: "lolaayinde@gmail.com" # Replace with your actual email
      storage: "/etc/traefik/acme.json"
      tlsChallenge: {}

tls:
  options:
    default:
      sniStrict: true
      minVersion: "VersionTLS12"

api:
  dashboard: true
  insecure: false

log:
  level: "INFO"
